services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.17.4
    restart: unless-stopped
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    logging:
      driver: local
    ports:
      - 8120:8120
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## use self signed certs in docker volume,
      ## or mount your own signed certs.
      - ssl-certs:/etc/komodo/ssl
      ## manage repos in a docker volume,
      ## or change it to an accessible host directory.
      - repos:/etc/komodo/repos
      ## manage stack files in a docker volume,
      ## or change it to an accessible host directory.
      - ${PWD}/stacks:${PWD}/stacks
      - ./PASSKEY:/etc/komodo/PASSKEY
      ## Optionally mount a path to store compose files
      # - /path/to/compose:/host/compose
    environment:
      ## Full list: `https://github.com/moghtech/komodo/blob/main/config/periphery.config.toml`
      ## Configure the same passkey given to Komodo Core (KOMODO_PASSKEY)
      PERIPHERY_PASSKEYS_FILE: /etc/komodo/PASSKEY
      ## Adding IP here will ensure calling IP is in the list. (optional)
      PERIPHERY_ALLOWED_IPS:
      ## Enable HTTPS server
      PERIPHERY_SSL_ENABLED: true
      ## If the disk size is overreporting, can use one of these to
      ## whitelist / blacklist the disks to filter them, whichever is easier.
      ## Accepts comma separated list of paths.
      ## Usually whitelisting /etc/hostname gives correct size.
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos
      PERIPHERY_STACK_DIR: "${PWD}/stacks"

      version: "3.9"

  docker-socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      # Global read-only – disables every HTTP verb except GET/HEAD
      - POST=0
      # Only turn on the endpoints Uptime Kuma needs
      - CONTAINERS=1 # /containers/*  (list + stats)
      - EVENTS=1 # optional, for real-time events
      - VERSION=1 # /version ping
      - PING=1 # /_ping health-check
      - AUTH=1
      - USERNAME=kumamon
      - PASSWORD=${SOCKET_PROXY_PASS}
      # Everything else stays at the default 0 (disabled)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # mount host socket read-only
    read_only: true
    tmpfs:
      - /run # writeable scratch
    ports:
      - "${SOCKET_PORT}:2375"

volumes:
  ssl-certs:
  repos:
  stacks:
